api/urls.py
from django.conf.urls import url

from api import views

urlpatterns = [
    url(r'^api/speech-process/file/$', views.ProcessUploadedFile.as_view(), name='process-uploaded-file'),
]

home/urls.py
from django.conf.urls import url

from home import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
]

speechtotext/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^', include('api.urls', namespace='api')),
] + staticfiles_urlpatterns()

api/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

network/models.py
from django.db import models

# Create your models here.

nlp/models.py
from django.db import models

# Create your models here.

api/views.py
from datetime import datetime

from django import http
from django.utils.html import linebreaks
from django.views import generic

from api.repositories import SpeechToTextRepository
from api.tools import FFMPEG
from network.actions import SESSION_PLANNED_TASKS_NAME
from network.repositories import IntentClassifierRepository


class ProcessUploadedFile(generic.edit.ProcessFormView):

    def convert_file(self, file, format):
        ffmpeg = FFMPEG(format)
        converted_file = ffmpeg.run_process(file)
        setattr(converted_file, 'name', file.name)
        return converted_file

    def recognize(self, file, recognizer):
        try:
            if file.seekable():
                file.seek(0)
            recognizer_repo = SpeechToTextRepository(file, recognizer=recognizer)

            result_text = recognizer_repo.recognize()

            return result_text

        except:
            return ''

    def intent_response(self, request, text):
        classifier = IntentClassifierRepository.get_instance()

        best_prediction = classifier.best_prediction(text)

        response = linebreaks(classifier.response_to_intent(
            best_prediction['label'],
            best_prediction,
            query=text,
            request=request
        ))
        extra = {}
        if best_prediction['label'] in ('TasksPlanning', 'CleanupTasksList', 'ShowTasksList',):
            tasks = request.session.get(SESSION_PLANNED_TASKS_NAME, {})
            extra.update({
                'tasks': [
                        {'date': datetime.fromtimestamp(int(date)).strftime('%B, %d %I:%M %p'), 'task': task['text'].title()}
                        for date, task in tasks.items()
                    ]
            })

        response = {
            'request': text,
            'response': response,
            'best_prediction': {
                'label': best_prediction['label'],
                'probability': '%.2f' % (best_prediction['probability'] * 100),
            }
        }
        response.update(extra)

        return response

    def post(self, request, *args, **kwargs):
        self.request = request
        is_voice_recorder = request.POST.get('voice-recorder', False)
        is_uploaded_file = request.POST.get('uploaded-file', False)
        is_raw_text = request.POST.get('raw-text', False)

        text = 'Unknown request type.'

        if (is_uploaded_file or is_voice_recorder):
            if 'voice-file' not in request.FILES:
                return http.JsonResponse({
                    'error': 'File not found',
                })

            uploaded_file = request.FILES['voice-file']

            file = self.convert_file(uploaded_file, 'wav')

            text = self.recognize(file, 'recognize_sphinx')
            # self.recognize(file, 'recognize_google')
        elif is_raw_text:
            text = request.POST.get('raw-text-data')

        response = self.intent_response(request, text)

        return http.JsonResponse(response, safe=False)

home/views.py
from django.views import generic


class Index(generic.TemplateView):
    template_name = 'home/index.html'

network/views.py
from django.shortcuts import render

# Create your views here.

nlp/views.py
from django.shortcuts import render

# Create your views here.

home/templates/home/index.html
{% extends 'layouts/base.html' %}
{% load static from staticfiles %}

{% block extra-styles %}
    <link rel="stylesheet" href="{% static "home/css/home.css" %}">
{% endblock %}

{% block main %}
    <div class="container">
        <form class="form-horizontal" method="POST" action="{% url "api:process-uploaded-file" %}" enctype="multipart/form-data" data-plugin="ajax-upload">
            {% csrf_token %}

            <div class="controls">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="input-group">
                            <input type="text" name="raw-text-data" class="form-control" placeholder="Type in raw text..." required>
                            <span class="input-group-btn">
                                <button class="btn btn-info" type="button" data-plugin="raw-text-analyze">Send</button>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="row loader-icon" style="display: none;">
                    <div class="col-md-2 col-md-offset-5">
                        <span class="fa fa-spinner fa-spin"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2 col-md-offset-5">
                        <div class="form-group">
                            <input type="file" name="voice-file">
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2 col-md-offset-5">
                        <div class="form-group">
                            <button class="btn btn-primary" type="button" data-dialog="file"><span class="fa fa-upload"></span> Upload File</button>
                            <button class="btn btn-success" data-plugin="record-audio"><span class="fa fa-microphone"></span></button>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 col-md-offset-4">
                        <div class="form-group">
                            <audio id="data-player" controls style="display: none;"></audio>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-md-offset-3">
                <div class="form-group" id="analyzed-response-text"></div>
            </div>

            <div class="col-md-3">
                <ul id="tasks-list">

                </ul>
            </div>

        </form>
    </div>

    {% verbatim %}
    <script id="api-request" type="text/x-jquery-tmpl">
        <div class="message bg-success col-xs-10">
            <p>${request}</p>
        </div>
    </script>
    <script id="api-response" type="text/x-jquery-tmpl">
        <div class="message bg-info col-xs-10 col-xs-offset-2">
            <p>{%html response%}</p>
            {%if best_prediction%}
            <div class='message-tooltip'>
                <span class="fa fa-info-circle" data-toggle="tooltip" title="Intent Prediction: ${best_prediction.label}(${best_prediction.probability}%)"></span>
            </div>
            {%/if%}
        </div>
    </script>
    <script id="api-scheduler" type="text/x-jquery-tmpl">
        {%each(date, task) tasks%}
        <li><strong>${date}:&nbsp;</strong>${task}</li>
        {%/each%}
    </script>
    {% endverbatim %}
{% endblock %}

{% block extra-footer-js %}
    <script src="{% static 'recorderjs/recorder.min.js' %}"></script>
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

templates/layouts/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Assistant</title>

    <link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    {% block extra-styles %}{% endblock %}
</head>
<body>

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url "home:index" %}"><span class="fa fa-android"></span></a>
            </div>
        </div>
    </nav>
{% endblock %}

{% block main %}{% endblock %}

<script src="{% static 'jquery/jquery-3.2.1.js' %}"></script>
<script src="{% static 'jquery/jquery.tmpl.js' %}"></script>
<script src="{% static 'jquery/jquery.plugins.js' %}"></script>
<script src="{% static 'jquery/jquery.init.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7/js/bootstrap.js' %}"></script>

{% block extra-footer-js %}{% endblock %}

</body>
</html>